package lombok.delombok;

/* loaded from: com.usidqw.qwerklj.apk:lombok/delombok/DelombokResult.SCL.lombok */
public class DelombokResult {
    private final java.util.List<lombok.javac.CommentInfo> comments;
    private final java.util.List<java.lang.Integer> textBlockStarts;
    private final com.sun.tools.javac.tree.JCTree.JCCompilationUnit compilationUnit;
    private final boolean changed;
    private final lombok.delombok.FormatPreferences formatPreferences;

    public DelombokResult(java.util.List<lombok.javac.CommentInfo> r4, java.util.List<java.lang.Integer> r5, com.sun.tools.javac.tree.JCTree.JCCompilationUnit r6, boolean r7, lombok.delombok.FormatPreferences r8) {
            r3 = this;
            r0 = r3
            r0.<init>()
            r0 = r3
            r1 = r4
            r0.comments = r1
            r0 = r3
            r1 = r5
            r0.textBlockStarts = r1
            r0 = r3
            r1 = r6
            r0.compilationUnit = r1
            r0 = r3
            r1 = r7
            r0.changed = r1
            r0 = r3
            r1 = r8
            r0.formatPreferences = r1
            return
    }

    public void print(java.io.Writer r10) throws java.io.IOException {
            r9 = this;
            r0 = r9
            boolean r0 = r0.changed
            if (r0 != 0) goto L1b
            r0 = r9
            java.lang.CharSequence r0 = r0.getContent()
            r11 = r0
            r0 = r11
            if (r0 == 0) goto L1b
            r0 = r10
            r1 = r11
            java.lang.String r1 = r1.toString()
            r0.write(r1)
            return
        L1b:
            r0 = r9
            lombok.delombok.FormatPreferences r0 = r0.formatPreferences
            boolean r0 = r0.generateDelombokComment()
            if (r0 == 0) goto L42
            r0 = r10
            java.lang.String r1 = "// Generated by delombok at "
            r0.write(r1)
            r0 = r10
            java.util.Date r1 = new java.util.Date
            r2 = r1
            r2.<init>()
            java.lang.String r1 = java.lang.String.valueOf(r1)
            r0.write(r1)
            r0 = r10
            java.lang.String r1 = "line.separator"
            java.lang.String r1 = java.lang.System.getProperty(r1)
            r0.write(r1)
        L42:
            r0 = r9
            java.util.List<lombok.javac.CommentInfo> r0 = r0.comments
            boolean r0 = r0 instanceof com.sun.tools.javac.util.List
            if (r0 == 0) goto L57
            r0 = r9
            java.util.List<lombok.javac.CommentInfo> r0 = r0.comments
            com.sun.tools.javac.util.List r0 = (com.sun.tools.javac.util.List) r0
            r11 = r0
            goto L6b
        L57:
            r0 = r9
            java.util.List<lombok.javac.CommentInfo> r0 = r0.comments
            r1 = 0
            lombok.javac.CommentInfo[] r1 = new lombok.javac.CommentInfo[r1]
            java.lang.Object[] r0 = r0.toArray(r1)
            lombok.javac.CommentInfo[] r0 = (lombok.javac.CommentInfo[]) r0
            com.sun.tools.javac.util.List r0 = com.sun.tools.javac.util.List.from(r0)
            r11 = r0
        L6b:
            r0 = r9
            java.util.List<java.lang.Integer> r0 = r0.textBlockStarts
            int r0 = r0.size()
            int[] r0 = new int[r0]
            r12 = r0
            r0 = 0
            r13 = r0
            r0 = r9
            java.util.List<java.lang.Integer> r0 = r0.textBlockStarts
            java.util.Iterator r0 = r0.iterator()
            r15 = r0
            goto La0
        L88:
            r0 = r15
            java.lang.Object r0 = r0.next()
            java.lang.Integer r0 = (java.lang.Integer) r0
            int r0 = r0.intValue()
            r14 = r0
            r0 = r12
            r1 = r13
            int r13 = r13 + 1
            r2 = r14
            r0[r1] = r2
        La0:
            r0 = r15
            boolean r0 = r0.hasNext()
            if (r0 != 0) goto L88
            lombok.delombok.FormatPreferenceScanner r0 = new lombok.delombok.FormatPreferenceScanner
            r1 = r0
            r1.<init>()
            r1 = r9
            lombok.delombok.FormatPreferences r1 = r1.formatPreferences
            r2 = r9
            java.lang.CharSequence r2 = r2.getContent()
            lombok.delombok.FormatPreferences r0 = r0.scan(r1, r2)
            r14 = r0
            r0 = r9
            com.sun.tools.javac.tree.JCTree$JCCompilationUnit r0 = r0.compilationUnit
            lombok.delombok.PrettyPrinter r1 = new lombok.delombok.PrettyPrinter
            r2 = r1
            r3 = r10
            r4 = r9
            com.sun.tools.javac.tree.JCTree$JCCompilationUnit r4 = r4.compilationUnit
            r5 = r11
            r6 = r12
            r7 = r14
            r2.<init>(r3, r4, r5, r6, r7)
            r0.accept(r1)
            return
    }

    private java.lang.CharSequence getContent() throws java.io.IOException {
            r3 = this;
            r0 = r3
            com.sun.tools.javac.tree.JCTree$JCCompilationUnit r0 = r0.compilationUnit
            javax.tools.JavaFileObject r0 = r0.getSourceFile()
            r4 = r0
            r0 = r4
            if (r0 != 0) goto Le
            r0 = 0
            return r0
        Le:
            r0 = r4
            r1 = 1
            java.lang.CharSequence r0 = r0.getCharContent(r1)
            return r0
    }

    public boolean isChanged() {
            r2 = this;
            r0 = r2
            boolean r0 = r0.changed
            return r0
    }
}
